### ISSUE TITLE
Error when not converging

### ISSUE THREAD

**Issue by strengejacke** [drizopoulos/GLMMadaptive#15]
I'm not sure whether this is intended or not... But when I fit a model that is not convering, an error occurs (instead of probably a warning?).

E.g. modifying your example from here:
https://drizopoulos.github.io/GLMMadaptive/articles/ZeroInflated_and_TwoPart_Models.html

```r
fm1 <- mixed_model(y ~ sex * time, random = ~ 1 | id, data = DF,
                   family = negative.binomial(), zi_fixed = ~ sex)
#> Error in while (iter < maxits && !converged) { : 
#>   missing value where TRUE/FALSE needed
```

This looks like a code-issue, but I'm not sure...

**Comment by drizopoulos** [comment]
The issue here is that you try to fit a model with a zero-inflated part, but you have not specified a zero-inflated family object. In particular, the internal optimization algorithm requires the log density function of the assumed distribution and the corresponding score vector. For the zero-inflated negative binomial these are provided in the family object `zi.negative.binomial()` but not in the `negative.binomial()` object.

I could but a warning regarding this, but this will not cover situations of user-defined family objects.

**Comment by strengejacke** [comment]
Ok thanks for clarification. Maybe you could still give users a hint of probable mistakes, like "did you specify the correct family" or so.

**Comment by drizopoulos** [comment]
Yes, I’ve done that in the development version on GitHub.

Thanks!

Best,
Dimitris
