### ISSUE TITLE
Random intercept only for zero-inflated portion, not count portion

### ISSUE THREAD

**Issue by ajw11** [drizopoulos/GLMMadaptive#37]
I attempted to have a random intercept only for the zero-inflated part of the model but I was unable to proceed due to an error saying I needed an argument for "random" (i.e., the count part). It is possible to only have a random intercept for the zi portion?

**Comment by drizopoulos** [comment]
Indeed, this is not possible in the package.

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________
From: ajw11 ***@***.***>
Sent: Wednesday, July 21, 2021 2:04:30 AM
To: drizopoulos/GLMMadaptive ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [drizopoulos/GLMMadaptive] Random intercept only for zero-inflated portion, not count portion (#37)


I attempted to have a random intercept only for the zero-inflated part of the model but I was unable to proceed due to an error saying I needed an argument for "random" (i.e., the count part). It is possible to only have a random intercept for the zi portion?
